<?xml version="1.0"?>
<package format="3">
  <name>rc_car_bringup</name>
  <version>0.1.0</version>
  <description>Launch and configuration for the RC car.</description>
  <maintainer email="maintainer@example.com">Project maintainer</maintainer>
  <license>Proprietary</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>joy</exec_depend>
  <exec_depend>teleop_manager</exec_depend>
  <exec_depend>jetracer_driver</exec_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
